import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "vi" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Navbar
    "nav.chat": "Trò chuyện",
    "nav.contacts": "Danh bạ",
    "nav.profile": "Hồ sơ",
    "nav.logout": "Đăng xuất",
    "nav.login": "Đăng nhập",
    
    // User Search
    "userSearch.search": "Tìm kiếm",
    "userSearch.title": "Tìm kiếm người dùng",
    "userSearch.byUsername": "Username",
    "userSearch.byEmail": "Email",
    "userSearch.byPhone": "Số điện thoại",
    "userSearch.usernamePlaceholder": "Nhập username...",
    "userSearch.emailPlaceholder": "Nhập email...",
    "userSearch.phonePlaceholder": "Nhập số điện thoại...",
    "userSearch.noResults": "Không tìm thấy kết quả",
    "userSearch.hint": "Nhập để tìm kiếm người dùng",
    "userSearch.unknownUser": "Người dùng",
    "userSearch.error": "Không thể tạo cuộc trò chuyện",
    
    // Chat
    "chat.typeMessage": "Nhập tin nhắn...",
    "chat.online": "Đang hoạt động",
    "chat.offline": "Ngoại tuyến",
    "chat.typing": "đang nhập...",
    "chat.send": "Gửi",
    "chat.selectConversation": "Chọn cuộc trò chuyện để bắt đầu nhắn tin",
    "chat.noConversations": "Chưa có cuộc trò chuyện nào",
    "chat.startNew": "Nhấn nút + để bắt đầu chat",
    "chat.search": "Tìm kiếm hoặc bắt đầu cuộc trò chuyện mới",
    "chat.newChat": "Cuộc trò chuyện mới",
    "chat.pinnedMessages": "Tin nhắn đã ghim",
    "chat.wallpaper": "Hình nền",
    "chat.viewProfile": "Xem hồ sơ",
    "chat.mute": "Tắt thông báo",
    "chat.deleteChat": "Xóa cuộc trò chuyện",
    "chat.notificationOn": "Âm thanh thông báo: Bật",
    "chat.notificationOff": "Âm thanh thông báo: Tắt",
    "chat.newGroup": "Nhóm mới",
    "chat.newMessage": "Tin nhắn mới",
    "chat.starred": "Tin nhắn có gắn dấu sao",
    "chat.settings": "Cài đặt",
    "chat.sendError": "Lỗi gửi tin nhắn",
    "chat.sendErrorDesc": "Không thể gửi tin nhắn. Vui lòng thử lại.",
    "chat.edited": "Đã chỉnh sửa",
    "chat.editedDesc": "Tin nhắn đã được chỉnh sửa",
    "chat.recalled": "Đã thu hồi",
    "chat.recalledDesc": "Tin nhắn đã được thu hồi cho tất cả mọi người",
    "chat.forwarded": "Đã chuyển tiếp",
    "chat.forwardedDesc": "Tin nhắn đã được chuyển tiếp thành công",
    "chat.callRejected": "Cuộc gọi bị từ chối",
    "chat.callRejectedDesc": "Người dùng đã từ chối cuộc gọi của bạn",
    "chat.noResponse": "Không có phản hồi",
    "chat.micBlocked": "Quyền microphone bị chặn",
    "chat.micBlockedDesc": "Vui lòng cho phép truy cập microphone trong cài đặt trình duyệt",
    "chat.cameraBlocked": "Quyền camera bị chặn",
    "chat.cameraBlockedDesc": "Vui lòng cho phép truy cập camera trong cài đặt trình duyệt",
    
    // Auth
    "auth.signIn": "Đăng nhập",
    "auth.signUp": "Đăng ký",
    "auth.email": "Email",
    "auth.password": "Mật khẩu",
    "auth.username": "Tên người dùng",
    "auth.forgotPassword": "Quên mật khẩu?",
    "auth.phone": "Số điện thoại",
    "auth.emailMethod": "Email",
    "auth.phoneMethod": "Điện thoại",
    "auth.welcome": "Fun Chat WEB3",
    "auth.welcomeDesc": "Kết nối và chia sẻ với bạn bè",
    "auth.emailExists": "Email đã tồn tại",
    "auth.emailExistsDesc": "Email này đã được đăng ký. Vui lòng đăng nhập hoặc sử dụng email khác.",
    "auth.registerError": "Lỗi đăng ký",
    "auth.registerSuccess": "Đăng ký thành công!",
    "auth.registerSuccessDesc": "Vui lòng kiểm tra email để xác nhận tài khoản.",
    "auth.validationError": "Lỗi validation",
    "auth.invalidCredentials": "Thông tin đăng nhập không đúng",
    "auth.invalidCredentialsDesc": "Email hoặc mật khẩu không chính xác. Vui lòng thử lại.",
    "auth.loginError": "Lỗi đăng nhập",
    "auth.otpSent": "Đã gửi mã OTP",
    "auth.otpSentDesc": "Mã xác thực đã được gửi đến",
    "auth.otpInvalid": "Mã OTP không hợp lệ",
    "auth.otpInvalidDesc": "Vui lòng nhập đủ 6 số",
    "auth.otpWrong": "Mã OTP không đúng",
    "auth.otpWrongDesc": "Vui lòng kiểm tra lại mã xác thực",
    "auth.loginSuccess": "Đăng nhập thành công!",
    "auth.loginSuccessDesc": "Chào mừng bạn đến với Fun Chat WEB3",
    "auth.enterOtp": "Nhập mã xác thực",
    "auth.otpSentTo": "Mã OTP đã được gửi đến",
    "auth.verify": "Xác nhận",
    "auth.verifying": "Đang xác thực...",
    "auth.noOtp": "Chưa nhận được mã?",
    "auth.resendOtp": "Gửi lại mã OTP",
    "auth.resendAfter": "Gửi lại sau",
    "auth.back": "Quay lại",
    "auth.emailConfirmed": "Email đã được xác nhận thành công!",
    "auth.redirecting": "Đang chuyển bạn vào Fun Chat WEB3...",
    "auth.sendOtp": "Gửi mã OTP",
    "auth.sending": "Đang gửi...",
    "auth.continueWith": "Hoặc tiếp tục với",
    "auth.noAccount": "Chưa có tài khoản?",
    "auth.hasAccount": "Đã có tài khoản?",
    "auth.resetPassword": "Đặt lại mật khẩu",
    "auth.resetPasswordDesc": "Nhập email để nhận link đặt lại mật khẩu",
    "auth.sendResetLink": "Gửi email đặt lại mật khẩu",
    "auth.emailSent": "Email đã được gửi",
    "auth.emailSentDesc": "Vui lòng kiểm tra hộp thư của bạn.",
    "auth.smsNotEnabled": "Chưa kích hoạt SMS",
    "auth.smsNotEnabledDesc": "Vui lòng liên hệ quản trị viên để kích hoạt đăng nhập bằng số điện thoại.",
    "auth.otpError": "Lỗi gửi OTP",
    "auth.emailNotVerified": "Email của bạn chưa được xác nhận.",
    "auth.emailNotVerifiedDesc": "Vui lòng kiểm tra hộp thư và nhấp vào link xác nhận.",
    "auth.resendEmail": "Gửi lại email",
    "auth.loggingIn": "Đang đăng nhập...",
    "auth.registering": "Đang đăng ký...",
    "auth.googleNotEnabled": "Google Sign-In chưa được kích hoạt",
    "auth.googleNotEnabledDesc": "Vui lòng liên hệ quản trị viên để kích hoạt đăng nhập bằng Google.",
    "auth.facebookNotEnabled": "Facebook Login chưa được kích hoạt",
    "auth.facebookNotEnabledDesc": "Vui lòng liên hệ quản trị viên để kích hoạt đăng nhập bằng Facebook.",
    "auth.oauthError": "Lỗi cấu hình OAuth",
    "auth.oauthErrorDesc": "Vui lòng kiểm tra cấu hình redirect URL.",
    "auth.googleError": "Lỗi đăng nhập Google",
    "auth.facebookError": "Lỗi đăng nhập Facebook",
    "auth.telegramDev": "Tính năng đăng nhập Telegram đang được phát triển.",
    "auth.signInWithGoogle": "Đăng nhập với Google",
    "auth.signInWithFacebook": "Đăng nhập với Facebook",
    "auth.signInWithTelegram": "Đăng nhập với Telegram",
    "auth.redirectingTo": "Đang chuyển hướng...",
    "auth.receiveOtp": "Nhận mã OTP",
    "auth.backToLogin": "Quay lại đăng nhập",
    
    // Friends
    "friends.title": "Danh bạ",
    "friends.search": "Tìm kiếm",
    "friends.requests": "Lời mời",
    "friends.list": "Danh sách",
    "friends.add": "Kết bạn",
    "friends.accept": "Chấp nhận",
    "friends.reject": "Từ chối",
    "friends.pending": "Đang chờ",
    "friends.message": "Nhắn tin",
    "friends.searchPlaceholder": "Tìm kiếm theo tên...",
    "friends.noResults": "Không tìm thấy người dùng",
    "friends.searchError": "Không thể tìm kiếm người dùng",
    "friends.noRequests": "Không có lời mời kết bạn",
    "friends.noFriends": "Chưa có bạn bè",
    "friends.noFriendsHint": "Hãy tìm kiếm và kết bạn với người khác",
    "friends.viewFriends": "Xem danh sách bạn bè",
    "friends.manageFriends": "Quản lý bạn bè",
    
    // Profile
    "profile.title": "Hồ sơ",
    "profile.edit": "Chỉnh sửa",
    "profile.editProfile": "Chỉnh sửa Profile",
    "profile.editProfileDesc": "Cập nhật thông tin cá nhân của bạn",
    "profile.friends": "Bạn bè",
    "profile.messages": "Tin nhắn",
    "profile.calls": "Cuộc gọi",
    "profile.overview": "Tổng quan",
    "profile.badges": "Huy hiệu",
    "profile.about": "Giới thiệu",
    "profile.socialLinks": "Liên kết xã hội",
    "profile.noBio": "Chưa có thông tin giới thiệu",
    "profile.job": "Công việc",
    "profile.location": "Địa điểm",
    "profile.pleaseLogin": "Vui lòng đăng nhập để xem profile",
    "profile.loadError": "Không thể tải dữ liệu profile",
    "profile.info": "Thông tin",
    "profile.social": "Mạng xã hội",
    "profile.coverPhoto": "Ảnh bìa",
    "profile.avatar": "Avatar",
    "profile.avatarHint": "Click vào avatar để thay đổi ảnh",
    "profile.avatarFormat": "Định dạng: JPG, PNG. Tối đa 10MB",
    "profile.username": "Tên người dùng",
    "profile.usernamePlaceholder": "Nhập tên người dùng",
    "profile.jobPlaceholder": "VD: Software Engineer",
    "profile.locationPlaceholder": "VD: Hồ Chí Minh, Việt Nam",
    "profile.bioPlaceholder": "Viết vài dòng về bạn...",
    "profile.uploadSuccess": "Thành công",
    "profile.avatarUploaded": "Đã tải lên avatar",
    "profile.coverUploaded": "Đã tải lên ảnh bìa",
    "profile.uploadError": "Không thể tải lên",
    "profile.updateSuccess": "Profile đã được cập nhật",
    "profile.updateError": "Không thể cập nhật profile",
    "profile.saveChanges": "Lưu thay đổi",
    
    // Common
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.delete": "Xóa",
    "common.confirm": "Xác nhận",
    "common.loading": "Đang tải...",
    "common.error": "Lỗi",
    "common.success": "Thành công",
    "common.retry": "Thử lại",
    "common.close": "Đóng",
    "common.user": "Người dùng",
  },
  en: {
    // Navbar
    "nav.chat": "Chat",
    "nav.contacts": "Contacts",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.login": "Login",
    
    // User Search
    "userSearch.search": "Search",
    "userSearch.title": "Search Users",
    "userSearch.byUsername": "Username",
    "userSearch.byEmail": "Email",
    "userSearch.byPhone": "Phone",
    "userSearch.usernamePlaceholder": "Enter username...",
    "userSearch.emailPlaceholder": "Enter email...",
    "userSearch.phonePlaceholder": "Enter phone number...",
    "userSearch.noResults": "No results found",
    "userSearch.hint": "Type to search users",
    "userSearch.unknownUser": "User",
    "userSearch.error": "Could not create conversation",
    
    // Chat
    "chat.typeMessage": "Type a message...",
    "chat.online": "Online",
    "chat.offline": "Offline",
    "chat.typing": "typing...",
    "chat.send": "Send",
    "chat.selectConversation": "Select a conversation to start messaging",
    "chat.noConversations": "No conversations yet",
    "chat.startNew": "Press + to start chatting",
    "chat.search": "Search or start a new conversation",
    "chat.newChat": "New conversation",
    "chat.pinnedMessages": "Pinned messages",
    "chat.wallpaper": "Wallpaper",
    "chat.viewProfile": "View profile",
    "chat.mute": "Mute notifications",
    "chat.deleteChat": "Delete chat",
    "chat.notificationOn": "Sound notifications: On",
    "chat.notificationOff": "Sound notifications: Off",
    "chat.newGroup": "New group",
    "chat.newMessage": "New message",
    "chat.starred": "Starred messages",
    "chat.settings": "Settings",
    "chat.sendError": "Send error",
    "chat.sendErrorDesc": "Could not send message. Please try again.",
    "chat.edited": "Edited",
    "chat.editedDesc": "Message has been edited",
    "chat.recalled": "Recalled",
    "chat.recalledDesc": "Message has been recalled for everyone",
    "chat.forwarded": "Forwarded",
    "chat.forwardedDesc": "Message has been forwarded successfully",
    "chat.callRejected": "Call rejected",
    "chat.callRejectedDesc": "User declined your call",
    "chat.noResponse": "No response",
    "chat.micBlocked": "Microphone blocked",
    "chat.micBlockedDesc": "Please allow microphone access in browser settings",
    "chat.cameraBlocked": "Camera blocked",
    "chat.cameraBlockedDesc": "Please allow camera access in browser settings",
    
    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.username": "Username",
    "auth.forgotPassword": "Forgot password?",
    "auth.phone": "Phone number",
    "auth.emailMethod": "Email",
    "auth.phoneMethod": "Phone",
    "auth.welcome": "Fun Chat WEB3",
    "auth.welcomeDesc": "Connect and share with friends",
    "auth.emailExists": "Email already exists",
    "auth.emailExistsDesc": "This email is already registered. Please sign in or use a different email.",
    "auth.registerError": "Registration error",
    "auth.registerSuccess": "Registration successful!",
    "auth.registerSuccessDesc": "Please check your email to confirm your account.",
    "auth.validationError": "Validation error",
    "auth.invalidCredentials": "Invalid credentials",
    "auth.invalidCredentialsDesc": "Email or password is incorrect. Please try again.",
    "auth.loginError": "Login error",
    "auth.otpSent": "OTP sent",
    "auth.otpSentDesc": "Verification code has been sent to",
    "auth.otpInvalid": "Invalid OTP",
    "auth.otpInvalidDesc": "Please enter all 6 digits",
    "auth.otpWrong": "Wrong OTP",
    "auth.otpWrongDesc": "Please check your verification code",
    "auth.loginSuccess": "Login successful!",
    "auth.loginSuccessDesc": "Welcome to Fun Chat WEB3",
    "auth.enterOtp": "Enter verification code",
    "auth.otpSentTo": "OTP has been sent to",
    "auth.verify": "Verify",
    "auth.verifying": "Verifying...",
    "auth.noOtp": "Didn't receive code?",
    "auth.resendOtp": "Resend OTP",
    "auth.resendAfter": "Resend after",
    "auth.back": "Go back",
    "auth.emailConfirmed": "Email confirmed successfully!",
    "auth.redirecting": "Redirecting to Fun Chat WEB3...",
    "auth.sendOtp": "Send OTP",
    "auth.sending": "Sending...",
    "auth.continueWith": "Or continue with",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.resetPassword": "Reset password",
    "auth.resetPasswordDesc": "Enter your email to receive a reset link",
    "auth.sendResetLink": "Send password reset email",
    "auth.emailSent": "Email sent",
    "auth.emailSentDesc": "Please check your inbox.",
    "auth.smsNotEnabled": "SMS not enabled",
    "auth.smsNotEnabledDesc": "Please contact admin to enable phone login.",
    "auth.otpError": "OTP error",
    "auth.emailNotVerified": "Your email is not verified.",
    "auth.emailNotVerifiedDesc": "Please check your inbox and click the confirmation link.",
    "auth.resendEmail": "Resend email",
    "auth.loggingIn": "Signing in...",
    "auth.registering": "Signing up...",
    "auth.googleNotEnabled": "Google Sign-In not enabled",
    "auth.googleNotEnabledDesc": "Please contact admin to enable Google login.",
    "auth.facebookNotEnabled": "Facebook Login not enabled",
    "auth.facebookNotEnabledDesc": "Please contact admin to enable Facebook login.",
    "auth.oauthError": "OAuth configuration error",
    "auth.oauthErrorDesc": "Please check redirect URL configuration.",
    "auth.googleError": "Google login error",
    "auth.facebookError": "Facebook login error",
    "auth.telegramDev": "Telegram login is under development.",
    "auth.signInWithGoogle": "Sign in with Google",
    "auth.signInWithFacebook": "Sign in with Facebook",
    "auth.signInWithTelegram": "Sign in with Telegram",
    "auth.redirectingTo": "Redirecting...",
    "auth.receiveOtp": "Get OTP",
    "auth.backToLogin": "Back to login",
    
    // Friends
    "friends.title": "Contacts",
    "friends.search": "Search",
    "friends.requests": "Requests",
    "friends.list": "List",
    "friends.add": "Add Friend",
    "friends.accept": "Accept",
    "friends.reject": "Reject",
    "friends.pending": "Pending",
    "friends.message": "Message",
    "friends.searchPlaceholder": "Search by name...",
    "friends.noResults": "No users found",
    "friends.searchError": "Could not search users",
    "friends.noRequests": "No friend requests",
    "friends.noFriends": "No friends yet",
    "friends.noFriendsHint": "Search and add friends",
    "friends.viewFriends": "View friends list",
    "friends.manageFriends": "Manage friends",
    
    // Profile
    "profile.title": "Profile",
    "profile.edit": "Edit",
    "profile.editProfile": "Edit Profile",
    "profile.editProfileDesc": "Update your personal information",
    "profile.friends": "Friends",
    "profile.messages": "Messages",
    "profile.calls": "Calls",
    "profile.overview": "Overview",
    "profile.badges": "Badges",
    "profile.about": "About",
    "profile.socialLinks": "Social Links",
    "profile.noBio": "No bio yet",
    "profile.job": "Job",
    "profile.location": "Location",
    "profile.pleaseLogin": "Please login to view profile",
    "profile.loadError": "Could not load profile data",
    "profile.info": "Information",
    "profile.social": "Social Media",
    "profile.coverPhoto": "Cover Photo",
    "profile.avatar": "Avatar",
    "profile.avatarHint": "Click on avatar to change photo",
    "profile.avatarFormat": "Format: JPG, PNG. Max 10MB",
    "profile.username": "Username",
    "profile.usernamePlaceholder": "Enter username",
    "profile.jobPlaceholder": "e.g. Software Engineer",
    "profile.locationPlaceholder": "e.g. Ho Chi Minh, Vietnam",
    "profile.bioPlaceholder": "Write something about yourself...",
    "profile.uploadSuccess": "Success",
    "profile.avatarUploaded": "Avatar uploaded",
    "profile.coverUploaded": "Cover photo uploaded",
    "profile.uploadError": "Upload failed",
    "profile.updateSuccess": "Profile updated",
    "profile.updateError": "Could not update profile",
    "profile.saveChanges": "Save changes",
    
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.confirm": "Confirm",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.retry": "Retry",
    "common.close": "Close",
    "common.user": "User",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "vi";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "vi" ? "en" : "vi"));
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
